name: Lint Python Code

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry lock
          poetry install

      - name: Run Ruff
        run: poetry run ruff check src --output-format=github

      - name: Run MyPy
        run: poetry run mypy src --follow-untyped-imports
